name: Run Both Discord Bots

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual start

jobs:
  run-discord-bots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      # ✅ Restore previous points JSON files (OG99 & FMLY)
      - name: Restore Previous Points JSON (OG99 & FMLY)
        uses: actions/cache@v3
        with:
          path: |
            previous_points_og99.json
            previous_points_fmly.json
          key: previous-points-${{ github.run_id }}
          restore-keys: previous-points-

      # ✅ Debug: Check if JSON files exist before running the bots
      - name: Debug JSON Persistence
        run: |
          if [ -f "previous_points_og99.json" ]; then
            echo "✅ OG99 JSON file exists. Showing contents:"
            cat previous_points_og99.json
          else
            echo "⚠ OG99 JSON file does not exist. First run?"
          fi
          
          if [ -f "previous_points_fmly.json" ]; then
            echo "✅ FMLY JSON file exists. Showing contents:"
            cat previous_points_fmly.json
          else
            echo "⚠ FMLY JSON file does not exist. First run?"
          fi

      # ✅ Run OG99 Bot
      - name: Run OG99 Bot
        env:
          DISCORD_TOKEN_OG99: ${{ secrets.DISCORD_TOKEN_OG99 }}
        run: python OG99-Bot.py &

      # ✅ Run FMLY Bot
      - name: Run FMLY Bot
        env:
          DISCORD_TOKEN_FMLY: ${{ secrets.DISCORD_TOKEN_FMLY }}
        run: python FMLYBot2.py

      # ✅ Save Updated JSON Files After the Bots Finish Running
      - name: Save Updated JSON Files
        run: |
          cp previous_points_og99.json $GITHUB_WORKSPACE/
          cp previous_points_fmly.json $GITHUB_WORKSPACE/
