name: Run Both Discord Bots

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  run-discord-bots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Upgrade Pip and Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore Previous Points JSON (OG99 & FMLY)
        uses: actions/cache@v3
        with:
          path: |
            previous_points_og99.json
            previous_points_fmly.json
          key: previous-points-${{ github.run_id }}
          restore-keys: |
            previous-points-

      - name: Debug JSON Persistence
        run: |
          if [ -f "previous_points_og99.json" ]; then
            echo "✅ OG99 JSON exists."
          else
            echo "{}" > previous_points_og99.json
            echo "⚠ OG99 JSON file was missing. Created an empty one."
          fi

          if [ -f "previous_points_fmly.json" ]; then
            echo "✅ FMLY JSON exists."
          else
            echo "{}" > previous_points_fmly.json
            echo "⚠ FMLY JSON file was missing. Created an empty one."
          fi

      - name: Run OG99 Bot
        env:
          DISCORD_TOKEN_OG99: ${{ secrets.DISCORD_TOKEN_OG99 }}
        run: python OG99-Bot.py &

      - name: Run FMLY Bot
        env:
          DISCORD_TOKEN_FMLY: ${{ secrets.DISCORD_TOKEN_FMLY }}
        run: python FMLYBot2.py &

      - name: Keep Workflow Running
        run: sleep 30 # Allow time for logs

      - name: Save Updated JSON Files
        uses: actions/cache@v3
        with:
          path: |
            previous_points_og99.json
            previous_points_fmly.json
          key: previous-points-${{ github.run_id }}
